version: '3.8'

services:
 server:
  container_name: 'node-server'
  build: .
  ports:
   - '8000:8000'
  environment:
   - PORT=${PORT}
   - DB_HOST=db
   - DB_PORT=${DB_PORT}
   - DB_USER=${DB_USER}
   - DB_PASSWORD=${DB_PASSWORD}
   - DB_NAME=${DB_NAME}
  depends_on:
   db:
    condition: service_healthy
 db:
  image: 'postgres'
  container_name: 'postgres-server'
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=${DB_PASSWORD}
   - POSTGRES_DB=${DB_NAME}
   - POSTGRES_USER=${DB_USER}
  volumes:
  - postgres_data:/var/lib/postgresql/data
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
   interval: 10s
   timeout: 5s
   retries: 5
   
volumes:
  postgres_data:
